"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import Navbar from "./navbar";
import { usePathname } from "next/navigation";
import { Toaster } from 'react-hot-toast';
import Providers from "../lib/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const disableNavbarPaths = ["/login", "/register", "/dashboard", "/dashboard/about"];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}

          <Toaster position="top-right" 
            toastOptions={{
              style: {
                borderRadius: "10px",
                padding: "16px",
              }
            }}
          />
        </Providers>
      </body>
    </html>
  );
}


