"use client";

import { useEffect } from "react";
// import type { Metadata } from "next";
import "../globals.css";
import { fetchUser } from "@/src/lib/api";
import { useRouter } from "next/navigation";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  useEffect(() => {
    const checkAuth = async () => {
      try {
        await fetchUser();
      } catch (error) {
        console.error("Error fetching user data:", error);
        router.push("/login");
      }

    };

    checkAuth();
  }, [router]);

  return (
      <div className="min-h-full flex flex-col">
        {children}
      </div>
  );
}


